name:        optparse-simple
version:     0.1.1
synopsis:    Simple interface to optparse-applicative
description: Please see the README at <https://www.stackage.org/package/optparse-simple>
category:    Options
author:      FP Complete
maintainer:  chrisdone@fpcomplete.com
copyright:   2015-2017 FP Complete
license:     BSD3
github:      fpco/optparse-simple

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.9.1 && <5

library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - template-haskell
  - optparse-applicative
  - githash >= 0.1.3.0
  - transformers >= 0.4
  when:
    - condition: impl (ghc < 8.0)
      dependencies: semigroups == 0.18.*
tests:
  test:
    main: Main.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - base
    - optparse-simple
    - directory
    - bytestring
